### ISSUE TITLE
楼主有没有关于权限管理的方法啊？针对这个项目的

### ISSUE THREAD

**Issue by demaweiliya** [harsima/vue-backend#13]
比如，角色管理，菜单管理，用户管理

**Comment by harsima** [comment]
关于权限管理这方面，我最近可能要有所调整，因为意识到了一个非常且致命的问题。

正常来说，在权限管理方面，前端能做的就是给出权限配置页面（比如页面访问权限和数据集权限等）操作后将记录传给后台，后台记录到数据库中。
然后在用户登录时，从后台获取这个用户拥有的权限，根据返回结果创建可访问菜单，这里可以控制页面访问权限（仅限展示）。
如果用户通过URL或修改代码等其他手段硬性访问，前端可以直接跳到403页面或者不做任何处理。

以上不管最终结果如何，你需要明确一点：前端只负责展示！
前端的权限管理说到最后也不过是为了让页面更好看一点，实际上是否能够操作数据或者查看数据，这个权限还是在接口上，所以，接口的权限才是真正的权限，其他的不过是辅助展示而已。

本项目目前已经有了权限管理的大致方法，你可以在我CSDN的博客上看到关于权限管理的整个流程。最近在细节中将会有所调整，但大体还是不变的。博文：[Vue + ElementUI 手撸后台管理网站基本框架(二)权限控制](http://blog.csdn.net/harsima/article/details/77949448)

**Comment by demaweiliya** [comment]
什么致命的问题？我都用上了

**Comment by harsima** [comment]
对我来说是致命的，在实际生产中只是显的啰嗦了。

上面我说了“前端只负责展示”，那么异步路由表的加载方式其实可以做更好的优化，哪怕直接加载全部的路由，然后通过自定义字段来确定菜单的多少也是可以的。这样用户如果透过更改URL地址等方式跳过前端的菜单配置，访问不在自己权限范围内的页面，则可以直接跳到403错误页面，这样修改可能会更加符合实际。

**Comment by demaweiliya** [comment]
你的意思是说将所有的路由都默认加载，只是去控制侧边栏，然后判断所要跳转的页面，不管是通过菜单还是修改地址栏，判断一下to的路径在不在某个权限数组里面这样来决定去不去403？就会省一个筛选路由的步骤？反正前台只是负责用户体验，做不到真正的权限控制？

**Comment by harsima** [comment]
你说的对，是这样子的。我现在的想法是只要让左侧菜单按照权限显示就行了，路由全加载。我还没试，所以还不知道是否可行

**Comment by wh-flysky** [comment]
楼主能解决下ie9 ie10不编译es5加载空白的问题吗
