### ISSUE TITLE
ERROR in Entry module not found: Error: Can't resolve './src/assets/style/theme-default.scss'

### ISSUE THREAD

**Issue by wangjin0821** [harsima/vue-backend#14]
ERROR in Entry module not found: Error: Can't resolve './src/assets/style/theme-default.scss' in 'E:
\vue'

  Build failed with errors.

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\b
in\\npm-cli.js" "run" "build"
npm ERR! node v6.11.4
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! vue-backend@0.1.0 build: `node build/build.js && node build/themeExtract.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vue-backend@0.1.0 build script 'node build/build.js && node build/themeExtrac
t.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the vue-backend package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build/build.js && node build/themeExtract.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs vue-backend
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls vue-backend
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\vue\npm-debug.log

**Comment by wangjin0821** [comment]
你好，项目刚刚下载下来安装好后，build就失败了 帮忙看下是什么问题？多谢

**Comment by harsima** [comment]
在`webpack.prod.conf.js`中修改`'theme-default'`为 './src/assets/css/theme-default.scss'`，这里是主题路径。

当前项目中还有很多BUG，请暂时当做学习使用。

**Comment by wangjin0821** [comment]
好的 谢谢
