### ISSUE TITLE
按钮权限未起作用

### ISSUE THREAD

**Issue by javalihuang** [harsima/vue-backend#17]
在navilist.js中将“完整示例--->列表页面”中的“edit”权限注释，如下：
<img width="267" alt="image" src="https://user-images.githubusercontent.com/33645617/38463999-956836e6-3b38-11e8-87cc-b63ca4cff3e1.png">
页面仍然显示“修改”按钮
<img width="946" alt="image" src="https://user-images.githubusercontent.com/33645617/38464003-b21efa04-3b38-11e8-865b-234e3a8567bb.png">
细看“hasPermission\index.js”这部分代码加了一个console.log，如下：
<img width="565" alt="image" src="https://user-images.githubusercontent.com/33645617/38463986-3db0f0e6-3b38-11e8-9364-8eb5fcd24361.png">
浏览器中查看：
<img width="951" alt="image" src="https://user-images.githubusercontent.com/33645617/38463993-5d43de46-3b38-11e8-86f1-a3b4ca9fc4e3.png">

**Comment by javalihuang** [comment]
刚才测试了一下，在navilist.js中放开“edit”权限，发现上图中的"permission list is undefined"这个应该是正确的。放开后，显示为
<img width="958" alt="image" src="https://user-images.githubusercontent.com/33645617/38464276-90d13f56-3b3d-11e8-9504-a3359da38fff.png">
可为什么注释“edit”权限，前端页面仍然会显示“修改”按钮呢？

**Comment by javalihuang** [comment]
harsima大牛，这个有方便交流的QQ群，或者微信群吗？

**Comment by harsima** [comment]
还是改一下条件判断，加入你说的情况。后面的判断是`permissionList`是否是数组，并且不包含传入的值。
```
if(!permissionList || (typeof (permissionList) == "object" && permissionList.length && !permissionList.includes(binding.value)))
```

**Comment by harsima** [comment]
刚才又看了一下，想说的是你对每个异步路由中或者说权限路由中的`permission`字段肯定没有全覆盖到。
需要权限的路由需要加入`permission`字段
```
path: '/table',
meta:{
     permission:[]
},
```

**Comment by harsima** [comment]
你可以修改该文件，以保证当前环境下好用：
```
if(!permissionList){
    console.error(`权限判断不生效。因路由中不包含permission字段，请检查路由表设置。当前路由地址：${vnode.context.$route.path}`)
    return
}
if(typeof (permissionList) != "object" || !permissionList.length){
    console.error(`权限判断不生效。因路由中permission字段非数组类型或内容为空，请检查路由表设置。当前路由地址：${vnode.context.$route.path}`)
    return
}
if(!permissionList.includes(binding.value)){
    el.parentNode.removeChild(el)
}
```

**Comment by javalihuang** [comment]
只改了一下判断条件，已经生效了 O(∩_∩)O

**Comment by harsima** [comment]
@javalihuang QQ交流群刚刚创建：745454791
