### ISSUE TITLE
分页条数问题

### ISSUE THREAD

**Issue by javalihuang** [harsima/vue-backend#20]
分页默认显示为10条，当数据超过10条，没有分页，在共多少条数据的地方，仍然显示为共10条。
![image](https://user-images.githubusercontent.com/33645617/38910323-599c5924-42fb-11e8-84e8-bf00a2fc31ae.png)

**Comment by javalihuang** [comment]
上面有两个问题点：
1. 一页显示为10条，实际数据有15条，没有分页；
2. 数据总数是15条，但共X条，X显示10；

**Comment by harsima** [comment]
建议你再看看element中分页组件的用法。数据总数和每页显示条数都应该和table中的实际数据进行绑定
