### ISSUE TITLE
vue-backend@1.2.0 dev d：\ 1前端\ 1.。页面\ element \ vue-ba  node build / dev-server.js  出现这个问题怎么解决我想问一下谢谢

### ISSUE THREAD

**Issue by qingshixun520luoz** [harsima/vue-backend#25]
vue-backend@1.2.0 dev d：\ 1前端\ 1.。页面\ element \ vue-ba 
node build / dev-server.js 
出现这个问题怎么解决我想问一下谢谢

**Comment by harsima** [comment]
对文件路径做修改，采用全英文路径试试，如果可以的话，请反馈
