### ISSUE TITLE
请问一下递归的菜单怎么添加 事件 例如点击事件

### ISSUE THREAD

**Issue by shiliangL** [harsima/vue-backend#4]
<template>
    <el-submenu v-if="item.child && item.child.length" :index="navIndex"> 
        
        <template slot="title">{{ item.name }}</template>
        
        <nav-item 
            v-for="(subItem,i) in item.child" 
            :key="navIndex+'-'+i" 
            :navIndex="navIndex+'-'+i"
            :item="subItem" >
        </nav-item>
    </el-submenu>

    <el-menu-item v-else :index="item.path">{{ item.name }}</el-menu-item>
</template>
<script>
    export default {
        // 递归组件必须有name
        name: 'navItem',
        props: ['item','navIndex']
    }
</script>

**Comment by harsima** [comment]
你需要换一个思路。Element中的菜单点击事件是直接绑定在`<el-menu>`上的。

事件名称 | 说明 | 回调参数
-- | -- | --
select | 菜单激活回调 | index: 选中菜单项的 indexPath: 选中菜单项的 index path

可对所有的`<el-menu-item>`启作用。如有需要则通过判断index可以进行不同的操作

**Comment by shiliangL** [comment]
好的 谢谢

**Comment by harsima** [comment]
这里有两种解决方法，不清楚你要哪一种，所以就直接写具体方法了。

**第一种，更换思路，使用Element组件的select事件。**
这种方法是直接在`<el-menu>`上添加事件，可对所有的子菜单进行统一操作，如果有需要可以根据`index`或者`indexPath`进行条件判断。

> 事件名称 | 说明 | 回调参数
> -- | -- | --
> select | 菜单激活回调 | index: 选中菜单项的 indexPath: 选中菜单项的 index path

**第二种，我就是要加click，不管其他**
这种情况就直接在`<el-menu-item>`上直接加`click`就好，需要的参数直接带到你的方法中。

``` 
<template>
    <el-menu-item v-else :index="item.path" @click="showConsole(item.path)">{{ item.name }}</el-menu-item>
</template>

<script>
export default {
    methods: {
        showConsole(index){
            console.log(index)
        }
    }
}
</script>
```
