### ISSUE TITLE
npm run dev 报错怎么回事

### ISSUE THREAD

**Issue by zhangyuling37du** [harsima/vue-backend#7]
-  ERROR  Failed to compile with 30 errors                                                                                                                                                         15:36:53

 error  in ./src/page/components/ui/pageSection.vue

Syntax Error: Unexpected token {

 @ ./src/router/asyncRouter.js 78:21-65
 @ ./src/router/index.js
 @ ./src/main.dev.js
 @ multi ./build/dev-client ./src/main.dev.js

 error  in ./src/index.vue

Syntax Error: Unexpected token {

 @ ./src/main.dev.js 14:0-26
 @ multi ./build/dev-client ./src/main.dev.js

 error  in ./src/page/layout/layout.vue

Syntax Error: Unexpected token {

 @ ./src/router/index.js 58:21-53
 @ ./src/main.dev.js
 @ multi ./build/dev-client ./src/main.dev.js

 error  in ./src/page/home/home.vue

Syntax Error: Unexpected token {

 @ ./src/router/index.js 69:25-53
 @ ./src/main.dev.js
 @ multi ./build/dev-client ./src/main.dev.js

 error  in ./src/page/error/error.vue

Syntax Error: Unexpected token {

 @ ./src/router/index.js 77:21-51
 @ ./src/main.dev.js
 @ multi ./build/dev-client ./src/main.dev.js

 error  in ./src/page/error/401.vue

Syntax Error: Unexpected token {

 @ ./src/router/index.js 84:25-53
 @ ./src/main.dev.js
 @ multi ./build/dev-client ./src/main.dev.js

 error  in ./src/page/error/403.vue

Syntax Error: Unexpected token {

 @ ./src/router/index.js 91:25-53
 @ ./src/main.dev.js
 @ multi ./build/dev-client ./src/main.dev.js

 error  in ./src/page/error/404.vue

Syntax Error: Unexpected token {

 @ ./src/router/index.js 98:25-53
 @ ./src/main.dev.js
 @ multi ./build/dev-client ./src/main.dev.js

**Comment by harsima** [comment]
`npm install` 了吗？

**Comment by zhangyuling37du** [comment]
就是npm install 之后 npm run dev 报了好多路径错误

在 2018-01-31 16:22:33，"harsima" <notifications@github.com> 写道：


npm install 了吗？

**Comment by harsima** [comment]
请使用dev分支下的版本，当前dev分支下的工程是最新的，没有问题
